In [2]:
import pandas as pd
titanic = pd.read_csv(r'C:\Users\USER\Downloads\Telegram Desktop\titanic.csv')

In [3]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df=titanic.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 'columns')

In [5]:
target = titanic.Survived

In [6]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [7]:
inputs = df.drop(['Survived'],axis ="columns")

In [8]:
inputs.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [9]:
dummies = pd.get_dummies(inputs.Sex)

In [10]:
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [11]:
from sklearn.preprocessing import LabelEncoder
le_sex =  LabelEncoder()

In [12]:
inputs['Sex']=le_sex.fit_transform(inputs['Sex'])

In [13]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [19]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [20]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [23]:
inputs['Age'] = inputs.Age.fillna(inputs.Age.mean())

In [27]:
inputs.columns.isna().any()

False

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [41]:
from sklearn.naive_bayes import GaussianNB
model =GaussianNB()

In [42]:
model.fit(x_train,y_train)

GaussianNB()

In [43]:
model.score(x_test,y_test)

0.8100558659217877

In [44]:
model.predict(x_test[:10])

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [48]:
model.predict_proba(x_test[:10])

array([[0.95916103, 0.04083897],
       [0.95136537, 0.04863463],
       [0.95927493, 0.04072507],
       [0.96111369, 0.03888631],
       [0.02441131, 0.97558869],
       [0.07831634, 0.92168366],
       [0.05635062, 0.94364938],
       [0.02706068, 0.97293932],
       [0.27018723, 0.72981277],
       [0.95620236, 0.04379764]])

In [ ]:
_